var stanza1 = [
    "through the blackberry bushes",
    "but the thorns are just handlebars",
    "and the berries-----",
    "the berries dye our feet purple.",
    "The dirt is alive",
    "it grows like the sky",
    "and if we run fast enough",
    "pebbles are springs under our feet",    
    "and beetles move the heavy earth",
    ">>",
    "lay down in the soil",
    "and inhale",
    "it smells like sweat salted summer",
    "carrots are orange whales that rise from the seas",
    "one will last you a winter.",
    "We can rest in the shade of a holed cabbage",
    "look at your hands",
    "see how they are speckled with sun."
]
